/**
 * {@link com.peninsula.frc2022.auto.AutoBase}'s placed in this package will automatically be
 * detected by {@link com.peninsula.frc2022.robot.AutoSelector}. This makes them visible for the
 * selector in Control Center, and also selectable via their name with {@link
 * com.peninsula.frc2022.robot.AutoSelector#setAuto(String)}. Their name is generated by default
 * from the class name via {@link com.peninsula.frc2022.auto.AutoBase#getName()}
 */
package com.peninsula.frc2022.auto;
